version: '3'

volumes:
  user_test_db:


services:
  user_service:
    container_name: ns-user-service-test
    build:
      dockerfile: Dockerfile.test
      context: .
    ports:
      - '8081:8000'
    depends_on:
      - user_db_test
    environment:
      DATABASE_HOST: user_db_test
      DATABASE_PORT: 5432

  user_db_test:
    image: postgres
    restart: always
    container_name: ns-user-db-test
    env_file:
      - .env
    ports:
      - '32700:5432'
    volumes:
      - user_test_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${TEST_DATABASE_NAME}
