version: '3'

volumes:
  user_db:

services:

  user_service:
    container_name: ns-user-service
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - user_db
    ports:
      - '8081:8000'
    depends_on:
      - user_db
    environment:
      DATABASE_HOST: user_db
      DATABASE_PORT: 5432
      JAEGER_AGENT_HOST: jaeger-all-in-one
      JWT_SECRETE: jwt_secrete

  user_db:
    image: postgres
    restart: always
    container_name: ns-user-db
    ports:
      - '32700:5432'
    volumes:
      - user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: ecommerce

  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one
    environment:
      - JAEGER_DISABLED=false
    expose:
      - "16686"
      - "6831/udp"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
