version: '3'

volumes:
  user_db:

services:

#  user_service:
#    container_name: ns-user-service
#    build:
#      dockerfile: Dockerfile
#      context: .
#    links:
#      - user_db
#    ports:
#      - '8080:8080'
#    depends_on:
#      - user_db
#    environment:
#      EE_DATABASE_URL: postgresql://note_root:root@user_db:5432/note_user

  user_db:
    image: postgres
    restart: always
    container_name: ns-user-db
    ports:
      - '32700:5432'
    volumes:
      - user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: ecommerce
