version: '3'

volumes:
  user_db:

services:

  user_service:
    container_name: ns-user-service
    build:
      dockerfile: Dockerfile
      context: .
    links:
      - user_db
    ports:
      - '8081:8000'
    depends_on:
      - user_db
    environment:
      DATABASE_HOST: user_db
      DATABASE_PORT: 5432


  user_db:
    image: postgres
    restart: always
    container_name: ns-user-db
    ports:
      - '32700:5432'
    volumes:
      - user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_MULTIPLE_DATABASES: ecommerce,test_ecommerce
